// Code generated by protoc-gen-go. DO NOT EDIT.
// source: HallService.proto

package HallService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateHallMessage struct {
	HallName             string   `protobuf:"bytes,1,opt,name=hallName,proto3" json:"hallName,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	SeatsPerRow          int32    `protobuf:"varint,3,opt,name=seatsPerRow,proto3" json:"seatsPerRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHallMessage) Reset()         { *m = CreateHallMessage{} }
func (m *CreateHallMessage) String() string { return proto.CompactTextString(m) }
func (*CreateHallMessage) ProtoMessage()    {}
func (*CreateHallMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{0}
}

func (m *CreateHallMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHallMessage.Unmarshal(m, b)
}
func (m *CreateHallMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHallMessage.Marshal(b, m, deterministic)
}
func (m *CreateHallMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHallMessage.Merge(m, src)
}
func (m *CreateHallMessage) XXX_Size() int {
	return xxx_messageInfo_CreateHallMessage.Size(m)
}
func (m *CreateHallMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHallMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHallMessage proto.InternalMessageInfo

func (m *CreateHallMessage) GetHallName() string {
	if m != nil {
		return m.HallName
	}
	return ""
}

func (m *CreateHallMessage) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CreateHallMessage) GetSeatsPerRow() int32 {
	if m != nil {
		return m.SeatsPerRow
	}
	return 0
}

type CreateHallResponse struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHallResponse) Reset()         { *m = CreateHallResponse{} }
func (m *CreateHallResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHallResponse) ProtoMessage()    {}
func (*CreateHallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{1}
}

func (m *CreateHallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHallResponse.Unmarshal(m, b)
}
func (m *CreateHallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHallResponse.Marshal(b, m, deterministic)
}
func (m *CreateHallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHallResponse.Merge(m, src)
}
func (m *CreateHallResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHallResponse.Size(m)
}
func (m *CreateHallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHallResponse proto.InternalMessageInfo

func (m *CreateHallResponse) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type DeleteHallMessage struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHallMessage) Reset()         { *m = DeleteHallMessage{} }
func (m *DeleteHallMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteHallMessage) ProtoMessage()    {}
func (*DeleteHallMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{2}
}

func (m *DeleteHallMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHallMessage.Unmarshal(m, b)
}
func (m *DeleteHallMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHallMessage.Marshal(b, m, deterministic)
}
func (m *DeleteHallMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHallMessage.Merge(m, src)
}
func (m *DeleteHallMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteHallMessage.Size(m)
}
func (m *DeleteHallMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHallMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHallMessage proto.InternalMessageInfo

func (m *DeleteHallMessage) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type DeleteHallResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHallResponse) Reset()         { *m = DeleteHallResponse{} }
func (m *DeleteHallResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteHallResponse) ProtoMessage()    {}
func (*DeleteHallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{3}
}

func (m *DeleteHallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHallResponse.Unmarshal(m, b)
}
func (m *DeleteHallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHallResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHallResponse.Merge(m, src)
}
func (m *DeleteHallResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHallResponse.Size(m)
}
func (m *DeleteHallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHallResponse proto.InternalMessageInfo

func (m *DeleteHallResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetHallMessage struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	Rows                 string   `protobuf:"bytes,2,opt,name=rows,proto3" json:"rows,omitempty"`
	SeatsPerRow          string   `protobuf:"bytes,3,opt,name=seatsPerRow,proto3" json:"seatsPerRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHallMessage) Reset()         { *m = GetHallMessage{} }
func (m *GetHallMessage) String() string { return proto.CompactTextString(m) }
func (*GetHallMessage) ProtoMessage()    {}
func (*GetHallMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{4}
}

func (m *GetHallMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHallMessage.Unmarshal(m, b)
}
func (m *GetHallMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHallMessage.Marshal(b, m, deterministic)
}
func (m *GetHallMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHallMessage.Merge(m, src)
}
func (m *GetHallMessage) XXX_Size() int {
	return xxx_messageInfo_GetHallMessage.Size(m)
}
func (m *GetHallMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHallMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetHallMessage proto.InternalMessageInfo

func (m *GetHallMessage) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

func (m *GetHallMessage) GetRows() string {
	if m != nil {
		return m.Rows
	}
	return ""
}

func (m *GetHallMessage) GetSeatsPerRow() string {
	if m != nil {
		return m.SeatsPerRow
	}
	return ""
}

type GetHallResponse struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	HallName             string   `protobuf:"bytes,2,opt,name=hallName,proto3" json:"hallName,omitempty"`
	Rows                 int32    `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	SeatsPerRow          int32    `protobuf:"varint,4,opt,name=seatsPerRow,proto3" json:"seatsPerRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHallResponse) Reset()         { *m = GetHallResponse{} }
func (m *GetHallResponse) String() string { return proto.CompactTextString(m) }
func (*GetHallResponse) ProtoMessage()    {}
func (*GetHallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{5}
}

func (m *GetHallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHallResponse.Unmarshal(m, b)
}
func (m *GetHallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHallResponse.Marshal(b, m, deterministic)
}
func (m *GetHallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHallResponse.Merge(m, src)
}
func (m *GetHallResponse) XXX_Size() int {
	return xxx_messageInfo_GetHallResponse.Size(m)
}
func (m *GetHallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHallResponse proto.InternalMessageInfo

func (m *GetHallResponse) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

func (m *GetHallResponse) GetHallName() string {
	if m != nil {
		return m.HallName
	}
	return ""
}

func (m *GetHallResponse) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *GetHallResponse) GetSeatsPerRow() int32 {
	if m != nil {
		return m.SeatsPerRow
	}
	return 0
}

type VerifySeatMessage struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	SeatID               int32    `protobuf:"varint,2,opt,name=seatID,proto3" json:"seatID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySeatMessage) Reset()         { *m = VerifySeatMessage{} }
func (m *VerifySeatMessage) String() string { return proto.CompactTextString(m) }
func (*VerifySeatMessage) ProtoMessage()    {}
func (*VerifySeatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{6}
}

func (m *VerifySeatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySeatMessage.Unmarshal(m, b)
}
func (m *VerifySeatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySeatMessage.Marshal(b, m, deterministic)
}
func (m *VerifySeatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySeatMessage.Merge(m, src)
}
func (m *VerifySeatMessage) XXX_Size() int {
	return xxx_messageInfo_VerifySeatMessage.Size(m)
}
func (m *VerifySeatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySeatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySeatMessage proto.InternalMessageInfo

func (m *VerifySeatMessage) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

func (m *VerifySeatMessage) GetSeatID() int32 {
	if m != nil {
		return m.SeatID
	}
	return 0
}

type VerifySeatResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySeatResponse) Reset()         { *m = VerifySeatResponse{} }
func (m *VerifySeatResponse) String() string { return proto.CompactTextString(m) }
func (*VerifySeatResponse) ProtoMessage()    {}
func (*VerifySeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8305e37cc059905c, []int{7}
}

func (m *VerifySeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySeatResponse.Unmarshal(m, b)
}
func (m *VerifySeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySeatResponse.Marshal(b, m, deterministic)
}
func (m *VerifySeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySeatResponse.Merge(m, src)
}
func (m *VerifySeatResponse) XXX_Size() int {
	return xxx_messageInfo_VerifySeatResponse.Size(m)
}
func (m *VerifySeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySeatResponse proto.InternalMessageInfo

func (m *VerifySeatResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateHallMessage)(nil), "CreateHallMessage")
	proto.RegisterType((*CreateHallResponse)(nil), "CreateHallResponse")
	proto.RegisterType((*DeleteHallMessage)(nil), "DeleteHallMessage")
	proto.RegisterType((*DeleteHallResponse)(nil), "DeleteHallResponse")
	proto.RegisterType((*GetHallMessage)(nil), "GetHallMessage")
	proto.RegisterType((*GetHallResponse)(nil), "GetHallResponse")
	proto.RegisterType((*VerifySeatMessage)(nil), "VerifySeatMessage")
	proto.RegisterType((*VerifySeatResponse)(nil), "VerifySeatResponse")
}

func init() { proto.RegisterFile("HallService.proto", fileDescriptor_8305e37cc059905c) }

var fileDescriptor_8305e37cc059905c = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0xfa, 0x3f, 0x53, 0xf8, 0xf5, 0x97, 0x11, 0x24, 0xe4, 0x54, 0xf6, 0x24, 0x28, 0x7b,
	0xd0, 0x83, 0x1f, 0xa0, 0x05, 0xf5, 0xa0, 0xc8, 0x16, 0x3c, 0x0a, 0x31, 0x8c, 0x5a, 0x88, 0xa6,
	0xec, 0x46, 0x8b, 0xf8, 0x85, 0xfd, 0x18, 0x4e, 0xd2, 0xd8, 0x6d, 0x5c, 0x42, 0xbc, 0x75, 0x66,
	0xe7, 0xbd, 0xe9, 0x7b, 0x6f, 0x02, 0xc1, 0x65, 0x9c, 0xa6, 0x4b, 0xd2, 0xef, 0xab, 0x84, 0xe4,
	0x5a, 0x67, 0x79, 0x26, 0x08, 0x82, 0xb9, 0xa6, 0x38, 0xa7, 0xe2, 0xe9, 0x9a, 0x8c, 0x89, 0x9f,
	0x08, 0x23, 0x18, 0x3f, 0x73, 0x79, 0x13, 0xbf, 0x50, 0xe8, 0xcd, 0xbc, 0x23, 0x5f, 0xed, 0x6a,
	0x44, 0xe8, 0xeb, 0x6c, 0x63, 0xc2, 0x2e, 0xf7, 0x07, 0xaa, 0xfc, 0x8d, 0x33, 0x98, 0x18, 0xe6,
	0x30, 0xb7, 0xa4, 0x55, 0xb6, 0x09, 0x7b, 0xe5, 0xd3, 0x7e, 0x4b, 0x9c, 0x00, 0xda, 0x35, 0x8a,
	0xcc, 0x3a, 0x7b, 0x35, 0x84, 0x87, 0x30, 0x2c, 0x78, 0xaf, 0x16, 0xe5, 0x96, 0x81, 0xaa, 0x2a,
	0x71, 0x0c, 0xc1, 0x82, 0x52, 0xaa, 0xff, 0xa9, 0xa6, 0x61, 0x09, 0x68, 0x87, 0x77, 0xd4, 0x21,
	0x8c, 0xcc, 0x5b, 0x92, 0x30, 0xb6, 0x1c, 0x1f, 0xab, 0x9f, 0x52, 0xdc, 0xc3, 0xbf, 0x0b, 0xca,
	0xff, 0xc0, 0x5c, 0x93, 0xea, 0x37, 0x4b, 0xf5, 0xeb, 0x52, 0x3f, 0x61, 0x5a, 0xf1, 0xb7, 0xe9,
	0xac, 0xf9, 0xdc, 0x6d, 0xf0, 0xb9, 0xd7, 0xec, 0x73, 0xdf, 0xf5, 0x79, 0x0e, 0xc1, 0x1d, 0xe9,
	0xd5, 0xe3, 0xc7, 0x92, 0x9b, 0x6d, 0xfa, 0xb8, 0x5f, 0x60, 0xb9, 0xbf, 0x0d, 0xb3, 0xaa, 0x0a,
	0x47, 0x2d, 0x49, 0xbb, 0xa3, 0xa7, 0x5f, 0x1e, 0x4c, 0xf6, 0x2e, 0x0b, 0xcf, 0x01, 0x6c, 0xd8,
	0x88, 0xd2, 0x39, 0xb0, 0xe8, 0x40, 0xba, 0xd7, 0x20, 0x3a, 0x05, 0xd0, 0x46, 0xc9, 0x40, 0xe7,
	0x08, 0x18, 0xe8, 0x66, 0xcd, 0x40, 0x09, 0xa3, 0xca, 0x73, 0x9c, 0xca, 0x7a, 0xba, 0xd1, 0x7f,
	0xf9, 0x2b, 0x8e, 0xed, 0x22, 0xab, 0x90, 0x17, 0x39, 0x9e, 0xf1, 0x22, 0xd7, 0x02, 0xd1, 0x79,
	0x18, 0x96, 0x5f, 0xcd, 0xd9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x88, 0x82, 0x41, 0x4a,
	0x03, 0x00, 0x00,
}
