// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BookingService.proto

package BookingService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KillBookingsMessage struct {
	ShowID               int32    `protobuf:"varint,1,opt,name=showID,proto3" json:"showID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillBookingsMessage) Reset()         { *m = KillBookingsMessage{} }
func (m *KillBookingsMessage) String() string { return proto.CompactTextString(m) }
func (*KillBookingsMessage) ProtoMessage()    {}
func (*KillBookingsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{0}
}

func (m *KillBookingsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillBookingsMessage.Unmarshal(m, b)
}
func (m *KillBookingsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillBookingsMessage.Marshal(b, m, deterministic)
}
func (m *KillBookingsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillBookingsMessage.Merge(m, src)
}
func (m *KillBookingsMessage) XXX_Size() int {
	return xxx_messageInfo_KillBookingsMessage.Size(m)
}
func (m *KillBookingsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KillBookingsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KillBookingsMessage proto.InternalMessageInfo

func (m *KillBookingsMessage) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

type KillBookingsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillBookingsResponse) Reset()         { *m = KillBookingsResponse{} }
func (m *KillBookingsResponse) String() string { return proto.CompactTextString(m) }
func (*KillBookingsResponse) ProtoMessage()    {}
func (*KillBookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{1}
}

func (m *KillBookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillBookingsResponse.Unmarshal(m, b)
}
func (m *KillBookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillBookingsResponse.Marshal(b, m, deterministic)
}
func (m *KillBookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillBookingsResponse.Merge(m, src)
}
func (m *KillBookingsResponse) XXX_Size() int {
	return xxx_messageInfo_KillBookingsResponse.Size(m)
}
func (m *KillBookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillBookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillBookingsResponse proto.InternalMessageInfo

func (m *KillBookingsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateBookingMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,2,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                []int32  `protobuf:"varint,3,rep,packed,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingMessage) Reset()         { *m = CreateBookingMessage{} }
func (m *CreateBookingMessage) String() string { return proto.CompactTextString(m) }
func (*CreateBookingMessage) ProtoMessage()    {}
func (*CreateBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{2}
}

func (m *CreateBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingMessage.Unmarshal(m, b)
}
func (m *CreateBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingMessage.Marshal(b, m, deterministic)
}
func (m *CreateBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingMessage.Merge(m, src)
}
func (m *CreateBookingMessage) XXX_Size() int {
	return xxx_messageInfo_CreateBookingMessage.Size(m)
}
func (m *CreateBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingMessage proto.InternalMessageInfo

func (m *CreateBookingMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateBookingMessage) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *CreateBookingMessage) GetSeats() []int32 {
	if m != nil {
		return m.Seats
	}
	return nil
}

type CreateBookingResponse struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingResponse) Reset()         { *m = CreateBookingResponse{} }
func (m *CreateBookingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookingResponse) ProtoMessage()    {}
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{3}
}

func (m *CreateBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingResponse.Unmarshal(m, b)
}
func (m *CreateBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingResponse.Merge(m, src)
}
func (m *CreateBookingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookingResponse.Size(m)
}
func (m *CreateBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingResponse proto.InternalMessageInfo

func (m *CreateBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type ConfirmBookingMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            int32    `protobuf:"varint,2,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmBookingMessage) Reset()         { *m = ConfirmBookingMessage{} }
func (m *ConfirmBookingMessage) String() string { return proto.CompactTextString(m) }
func (*ConfirmBookingMessage) ProtoMessage()    {}
func (*ConfirmBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{4}
}

func (m *ConfirmBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmBookingMessage.Unmarshal(m, b)
}
func (m *ConfirmBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmBookingMessage.Marshal(b, m, deterministic)
}
func (m *ConfirmBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmBookingMessage.Merge(m, src)
}
func (m *ConfirmBookingMessage) XXX_Size() int {
	return xxx_messageInfo_ConfirmBookingMessage.Size(m)
}
func (m *ConfirmBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmBookingMessage proto.InternalMessageInfo

func (m *ConfirmBookingMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ConfirmBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type ConfirmBookingResponse struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmBookingResponse) Reset()         { *m = ConfirmBookingResponse{} }
func (m *ConfirmBookingResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmBookingResponse) ProtoMessage()    {}
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{5}
}

func (m *ConfirmBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmBookingResponse.Unmarshal(m, b)
}
func (m *ConfirmBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmBookingResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmBookingResponse.Merge(m, src)
}
func (m *ConfirmBookingResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmBookingResponse.Size(m)
}
func (m *ConfirmBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmBookingResponse proto.InternalMessageInfo

func (m *ConfirmBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type DeleteBookingMessage struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingMessage) Reset()         { *m = DeleteBookingMessage{} }
func (m *DeleteBookingMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingMessage) ProtoMessage()    {}
func (*DeleteBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{6}
}

func (m *DeleteBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingMessage.Unmarshal(m, b)
}
func (m *DeleteBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingMessage.Marshal(b, m, deterministic)
}
func (m *DeleteBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingMessage.Merge(m, src)
}
func (m *DeleteBookingMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingMessage.Size(m)
}
func (m *DeleteBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingMessage proto.InternalMessageInfo

func (m *DeleteBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type DeleteBookingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingResponse) Reset()         { *m = DeleteBookingResponse{} }
func (m *DeleteBookingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingResponse) ProtoMessage()    {}
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{7}
}

func (m *DeleteBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingResponse.Unmarshal(m, b)
}
func (m *DeleteBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingResponse.Merge(m, src)
}
func (m *DeleteBookingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingResponse.Size(m)
}
func (m *DeleteBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingResponse proto.InternalMessageInfo

func (m *DeleteBookingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserBookingsMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBookingsMessage) Reset()         { *m = GetUserBookingsMessage{} }
func (m *GetUserBookingsMessage) String() string { return proto.CompactTextString(m) }
func (*GetUserBookingsMessage) ProtoMessage()    {}
func (*GetUserBookingsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{8}
}

func (m *GetUserBookingsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBookingsMessage.Unmarshal(m, b)
}
func (m *GetUserBookingsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBookingsMessage.Marshal(b, m, deterministic)
}
func (m *GetUserBookingsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBookingsMessage.Merge(m, src)
}
func (m *GetUserBookingsMessage) XXX_Size() int {
	return xxx_messageInfo_GetUserBookingsMessage.Size(m)
}
func (m *GetUserBookingsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBookingsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBookingsMessage proto.InternalMessageInfo

func (m *GetUserBookingsMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserBookingsResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            []int32  `protobuf:"varint,2,rep,packed,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBookingsResponse) Reset()         { *m = GetUserBookingsResponse{} }
func (m *GetUserBookingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserBookingsResponse) ProtoMessage()    {}
func (*GetUserBookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{9}
}

func (m *GetUserBookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBookingsResponse.Unmarshal(m, b)
}
func (m *GetUserBookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBookingsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserBookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBookingsResponse.Merge(m, src)
}
func (m *GetUserBookingsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserBookingsResponse.Size(m)
}
func (m *GetUserBookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBookingsResponse proto.InternalMessageInfo

func (m *GetUserBookingsResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetUserBookingsResponse) GetBookingID() []int32 {
	if m != nil {
		return m.BookingID
	}
	return nil
}

type GetBookingMessage struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingMessage) Reset()         { *m = GetBookingMessage{} }
func (m *GetBookingMessage) String() string { return proto.CompactTextString(m) }
func (*GetBookingMessage) ProtoMessage()    {}
func (*GetBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{10}
}

func (m *GetBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingMessage.Unmarshal(m, b)
}
func (m *GetBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingMessage.Marshal(b, m, deterministic)
}
func (m *GetBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingMessage.Merge(m, src)
}
func (m *GetBookingMessage) XXX_Size() int {
	return xxx_messageInfo_GetBookingMessage.Size(m)
}
func (m *GetBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingMessage proto.InternalMessageInfo

func (m *GetBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type GetBookingResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,2,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                []int32  `protobuf:"varint,3,rep,packed,name=seats,proto3" json:"seats,omitempty"`
	BookingID            int32    `protobuf:"varint,4,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingResponse) Reset()         { *m = GetBookingResponse{} }
func (m *GetBookingResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookingResponse) ProtoMessage()    {}
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{11}
}

func (m *GetBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingResponse.Unmarshal(m, b)
}
func (m *GetBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingResponse.Marshal(b, m, deterministic)
}
func (m *GetBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingResponse.Merge(m, src)
}
func (m *GetBookingResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookingResponse.Size(m)
}
func (m *GetBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingResponse proto.InternalMessageInfo

func (m *GetBookingResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetBookingResponse) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *GetBookingResponse) GetSeats() []int32 {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *GetBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

func init() {
	proto.RegisterType((*KillBookingsMessage)(nil), "KillBookingsMessage")
	proto.RegisterType((*KillBookingsResponse)(nil), "KillBookingsResponse")
	proto.RegisterType((*CreateBookingMessage)(nil), "CreateBookingMessage")
	proto.RegisterType((*CreateBookingResponse)(nil), "CreateBookingResponse")
	proto.RegisterType((*ConfirmBookingMessage)(nil), "ConfirmBookingMessage")
	proto.RegisterType((*ConfirmBookingResponse)(nil), "ConfirmBookingResponse")
	proto.RegisterType((*DeleteBookingMessage)(nil), "DeleteBookingMessage")
	proto.RegisterType((*DeleteBookingResponse)(nil), "DeleteBookingResponse")
	proto.RegisterType((*GetUserBookingsMessage)(nil), "GetUserBookingsMessage")
	proto.RegisterType((*GetUserBookingsResponse)(nil), "GetUserBookingsResponse")
	proto.RegisterType((*GetBookingMessage)(nil), "GetBookingMessage")
	proto.RegisterType((*GetBookingResponse)(nil), "GetBookingResponse")
}

func init() { proto.RegisterFile("BookingService.proto", fileDescriptor_5dbbe29f60712d30) }

var fileDescriptor_5dbbe29f60712d30 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x05, 0x2a, 0xa8, 0x13, 0xc5, 0xb8, 0x6c, 0x4b, 0xd3, 0x78, 0x20, 0x7b, 0xf2, 0xe2, 0x06,
	0xbf, 0x4f, 0x26, 0x46, 0x88, 0xc6, 0x18, 0x62, 0x82, 0xf1, 0xe6, 0x05, 0xc8, 0x88, 0x8d, 0xc8,
	0x92, 0x2e, 0xa8, 0x7f, 0xc5, 0x7f, 0xeb, 0x04, 0x90, 0x76, 0xcb, 0xaa, 0xe5, 0x38, 0x4b, 0xdf,
	0xc7, 0xee, 0x7b, 0x0c, 0xf0, 0x2b, 0xa5, 0x5e, 0xc3, 0x61, 0xff, 0x01, 0xa3, 0xf7, 0xb0, 0x87,
	0x72, 0x14, 0xa9, 0xb1, 0x12, 0x07, 0x50, 0xb9, 0x0b, 0x07, 0x83, 0xf9, 0x6f, 0xba, 0x85, 0x5a,
	0x77, 0xfa, 0xc8, 0x3c, 0x28, 0xe9, 0x17, 0xf5, 0x71, 0xdb, 0xf4, 0xf3, 0xb5, 0xfc, 0x7e, 0xb1,
	0x3d, 0x9f, 0x44, 0x1d, 0x78, 0xf2, 0xf3, 0x36, 0xea, 0x91, 0x1a, 0x6a, 0x64, 0x3e, 0xac, 0xeb,
	0x49, 0xaf, 0x47, 0xe8, 0x29, 0x60, 0xa3, 0xfd, 0x33, 0x8a, 0x27, 0xe0, 0x8d, 0x08, 0x3b, 0x63,
	0x9c, 0x63, 0x12, 0x0a, 0x13, 0x8d, 0x51, 0xac, 0x30, 0x9b, 0x12, 0xca, 0x85, 0xa4, 0x32, 0xe3,
	0x50, 0xd4, 0x44, 0xa3, 0x7d, 0xa7, 0xe6, 0xd0, 0xf1, 0x6c, 0x10, 0xa7, 0xe0, 0x1a, 0xec, 0x0b,
	0x43, 0x7b, 0xb0, 0xd9, 0x9d, 0x1d, 0x2d, 0x14, 0xe2, 0x03, 0xd1, 0x22, 0x98, 0x1a, 0x3e, 0x87,
	0xd1, 0x5b, 0x46, 0x57, 0x06, 0x5d, 0x21, 0x4d, 0x77, 0x06, 0x9e, 0x49, 0x97, 0xd1, 0xc6, 0x09,
	0xf0, 0x26, 0x0e, 0x70, 0xe9, 0x6d, 0xfe, 0x46, 0x1d, 0x82, 0x6b, 0xa0, 0x32, 0x84, 0x50, 0x07,
	0xef, 0x06, 0xc7, 0x8f, 0x74, 0x17, 0x4b, 0xd0, 0xb6, 0x0b, 0x8b, 0x7b, 0xa8, 0xa6, 0x10, 0x0b,
	0x99, 0x8c, 0x6f, 0xe4, 0xa4, 0x5d, 0xef, 0x12, 0xe1, 0x4a, 0x17, 0xfd, 0x04, 0x16, 0x43, 0xfe,
	0x95, 0x5f, 0xa9, 0x38, 0xa6, 0xf2, 0x5a, 0x4a, 0xf9, 0xe8, 0xcb, 0x81, 0xb2, 0xf9, 0x77, 0x61,
	0x97, 0xb0, 0x6d, 0x34, 0x8d, 0xb9, 0xd2, 0xd6, 0xeb, 0xc0, 0x93, 0xd6, 0x42, 0x8a, 0x1c, 0x6b,
	0x40, 0xd9, 0x6c, 0x09, 0xa3, 0x6f, 0x6d, 0x2d, 0x0c, 0xaa, 0xd2, 0x5e, 0x27, 0x22, 0x21, 0x1b,
	0x46, 0xf8, 0x64, 0xc3, 0x56, 0x21, 0xb2, 0x61, 0xed, 0x08, 0x31, 0x5c, 0xc3, 0x4e, 0x2a, 0x59,
	0x56, 0x95, 0xf6, 0x76, 0x04, 0xbe, 0xfc, 0xa5, 0x04, 0xc4, 0x73, 0x0e, 0x10, 0xa7, 0xc3, 0x98,
	0x5c, 0x4a, 0x37, 0xa8, 0xc8, 0xe5, 0xf8, 0x08, 0x78, 0x01, 0x5b, 0xc9, 0x1d, 0xc2, 0xb8, 0xb4,
	0x6c, 0xa0, 0xc0, 0x95, 0xb6, 0x45, 0x23, 0x72, 0xdd, 0xd2, 0x74, 0x71, 0x1d, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x7c, 0xae, 0xd2, 0xd0, 0x04, 0x00, 0x00,
}
