// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BookingService.proto

package BookingService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareBookingMessage struct {
	ShowID               int32    `protobuf:"varint,1,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                []int32  `protobuf:"varint,2,rep,packed,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareBookingMessage) Reset()         { *m = PrepareBookingMessage{} }
func (m *PrepareBookingMessage) String() string { return proto.CompactTextString(m) }
func (*PrepareBookingMessage) ProtoMessage()    {}
func (*PrepareBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{0}
}

func (m *PrepareBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareBookingMessage.Unmarshal(m, b)
}
func (m *PrepareBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareBookingMessage.Marshal(b, m, deterministic)
}
func (m *PrepareBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareBookingMessage.Merge(m, src)
}
func (m *PrepareBookingMessage) XXX_Size() int {
	return xxx_messageInfo_PrepareBookingMessage.Size(m)
}
func (m *PrepareBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareBookingMessage proto.InternalMessageInfo

func (m *PrepareBookingMessage) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *PrepareBookingMessage) GetSeats() []int32 {
	if m != nil {
		return m.Seats
	}
	return nil
}

type PrepareBookingResponse struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareBookingResponse) Reset()         { *m = PrepareBookingResponse{} }
func (m *PrepareBookingResponse) String() string { return proto.CompactTextString(m) }
func (*PrepareBookingResponse) ProtoMessage()    {}
func (*PrepareBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{1}
}

func (m *PrepareBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareBookingResponse.Unmarshal(m, b)
}
func (m *PrepareBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareBookingResponse.Marshal(b, m, deterministic)
}
func (m *PrepareBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareBookingResponse.Merge(m, src)
}
func (m *PrepareBookingResponse) XXX_Size() int {
	return xxx_messageInfo_PrepareBookingResponse.Size(m)
}
func (m *PrepareBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareBookingResponse proto.InternalMessageInfo

func (m *PrepareBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type CreateBookingMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingMessage) Reset()         { *m = CreateBookingMessage{} }
func (m *CreateBookingMessage) String() string { return proto.CompactTextString(m) }
func (*CreateBookingMessage) ProtoMessage()    {}
func (*CreateBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{2}
}

func (m *CreateBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingMessage.Unmarshal(m, b)
}
func (m *CreateBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingMessage.Marshal(b, m, deterministic)
}
func (m *CreateBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingMessage.Merge(m, src)
}
func (m *CreateBookingMessage) XXX_Size() int {
	return xxx_messageInfo_CreateBookingMessage.Size(m)
}
func (m *CreateBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingMessage proto.InternalMessageInfo

func (m *CreateBookingMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type CreateBookingResponse struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingResponse) Reset()         { *m = CreateBookingResponse{} }
func (m *CreateBookingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookingResponse) ProtoMessage()    {}
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{3}
}

func (m *CreateBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingResponse.Unmarshal(m, b)
}
func (m *CreateBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingResponse.Merge(m, src)
}
func (m *CreateBookingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookingResponse.Size(m)
}
func (m *CreateBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingResponse proto.InternalMessageInfo

func (m *CreateBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type DeleteBookingMessage struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingMessage) Reset()         { *m = DeleteBookingMessage{} }
func (m *DeleteBookingMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingMessage) ProtoMessage()    {}
func (*DeleteBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{4}
}

func (m *DeleteBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingMessage.Unmarshal(m, b)
}
func (m *DeleteBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingMessage.Marshal(b, m, deterministic)
}
func (m *DeleteBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingMessage.Merge(m, src)
}
func (m *DeleteBookingMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingMessage.Size(m)
}
func (m *DeleteBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingMessage proto.InternalMessageInfo

func (m *DeleteBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type DeleteBookingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingResponse) Reset()         { *m = DeleteBookingResponse{} }
func (m *DeleteBookingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingResponse) ProtoMessage()    {}
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{5}
}

func (m *DeleteBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingResponse.Unmarshal(m, b)
}
func (m *DeleteBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingResponse.Merge(m, src)
}
func (m *DeleteBookingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingResponse.Size(m)
}
func (m *DeleteBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingResponse proto.InternalMessageInfo

func (m *DeleteBookingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserBookingsMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBookingsMessage) Reset()         { *m = GetUserBookingsMessage{} }
func (m *GetUserBookingsMessage) String() string { return proto.CompactTextString(m) }
func (*GetUserBookingsMessage) ProtoMessage()    {}
func (*GetUserBookingsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{6}
}

func (m *GetUserBookingsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBookingsMessage.Unmarshal(m, b)
}
func (m *GetUserBookingsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBookingsMessage.Marshal(b, m, deterministic)
}
func (m *GetUserBookingsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBookingsMessage.Merge(m, src)
}
func (m *GetUserBookingsMessage) XXX_Size() int {
	return xxx_messageInfo_GetUserBookingsMessage.Size(m)
}
func (m *GetUserBookingsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBookingsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBookingsMessage proto.InternalMessageInfo

func (m *GetUserBookingsMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserBookingsResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            []int32  `protobuf:"varint,2,rep,packed,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBookingsResponse) Reset()         { *m = GetUserBookingsResponse{} }
func (m *GetUserBookingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserBookingsResponse) ProtoMessage()    {}
func (*GetUserBookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{7}
}

func (m *GetUserBookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBookingsResponse.Unmarshal(m, b)
}
func (m *GetUserBookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBookingsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserBookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBookingsResponse.Merge(m, src)
}
func (m *GetUserBookingsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserBookingsResponse.Size(m)
}
func (m *GetUserBookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBookingsResponse proto.InternalMessageInfo

func (m *GetUserBookingsResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetUserBookingsResponse) GetBookingID() []int32 {
	if m != nil {
		return m.BookingID
	}
	return nil
}

type GetBookingMessage struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingMessage) Reset()         { *m = GetBookingMessage{} }
func (m *GetBookingMessage) String() string { return proto.CompactTextString(m) }
func (*GetBookingMessage) ProtoMessage()    {}
func (*GetBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{8}
}

func (m *GetBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingMessage.Unmarshal(m, b)
}
func (m *GetBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingMessage.Marshal(b, m, deterministic)
}
func (m *GetBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingMessage.Merge(m, src)
}
func (m *GetBookingMessage) XXX_Size() int {
	return xxx_messageInfo_GetBookingMessage.Size(m)
}
func (m *GetBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingMessage proto.InternalMessageInfo

func (m *GetBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type GetBookingResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,2,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                []int32  `protobuf:"varint,3,rep,packed,name=seats,proto3" json:"seats,omitempty"`
	BookingID            []int32  `protobuf:"varint,4,rep,packed,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingResponse) Reset()         { *m = GetBookingResponse{} }
func (m *GetBookingResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookingResponse) ProtoMessage()    {}
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{9}
}

func (m *GetBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingResponse.Unmarshal(m, b)
}
func (m *GetBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingResponse.Marshal(b, m, deterministic)
}
func (m *GetBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingResponse.Merge(m, src)
}
func (m *GetBookingResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookingResponse.Size(m)
}
func (m *GetBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingResponse proto.InternalMessageInfo

func (m *GetBookingResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetBookingResponse) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *GetBookingResponse) GetSeats() []int32 {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *GetBookingResponse) GetBookingID() []int32 {
	if m != nil {
		return m.BookingID
	}
	return nil
}

func init() {
	proto.RegisterType((*PrepareBookingMessage)(nil), "PrepareBookingMessage")
	proto.RegisterType((*PrepareBookingResponse)(nil), "PrepareBookingResponse")
	proto.RegisterType((*CreateBookingMessage)(nil), "CreateBookingMessage")
	proto.RegisterType((*CreateBookingResponse)(nil), "CreateBookingResponse")
	proto.RegisterType((*DeleteBookingMessage)(nil), "DeleteBookingMessage")
	proto.RegisterType((*DeleteBookingResponse)(nil), "DeleteBookingResponse")
	proto.RegisterType((*GetUserBookingsMessage)(nil), "GetUserBookingsMessage")
	proto.RegisterType((*GetUserBookingsResponse)(nil), "GetUserBookingsResponse")
	proto.RegisterType((*GetBookingMessage)(nil), "GetBookingMessage")
	proto.RegisterType((*GetBookingResponse)(nil), "GetBookingResponse")
}

func init() { proto.RegisterFile("BookingService.proto", fileDescriptor_5dbbe29f60712d30) }

var fileDescriptor_5dbbe29f60712d30 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xfb, 0xc7, 0x56, 0x1d, 0xb0, 0xe2, 0x98, 0xa4, 0x21, 0x78, 0x28, 0x7b, 0xf2, 0xb4,
	0xf8, 0xdf, 0xab, 0xd8, 0xaa, 0x78, 0x10, 0x25, 0xe2, 0x07, 0x48, 0xc3, 0x50, 0x8b, 0xd2, 0x0d,
	0xbb, 0xa9, 0xfa, 0x59, 0xfd, 0x34, 0x2e, 0x4d, 0x4c, 0xdc, 0x64, 0x6b, 0xf5, 0x38, 0xd3, 0xbe,
	0xf7, 0x66, 0x79, 0xbf, 0x80, 0x73, 0x29, 0xc4, 0xcb, 0x74, 0x36, 0x79, 0x24, 0xf9, 0x36, 0x8d,
	0x89, 0x27, 0x52, 0xa4, 0x82, 0x5d, 0x81, 0xfb, 0x20, 0x29, 0x89, 0x24, 0xe5, 0x3f, 0xdf, 0x91,
	0x52, 0xd1, 0x84, 0xd0, 0x83, 0xae, 0x7a, 0x16, 0xef, 0xb7, 0x23, 0xbf, 0x39, 0x68, 0xee, 0x77,
	0xc2, 0x7c, 0x42, 0x07, 0x3a, 0x8a, 0xa2, 0x54, 0xf9, 0xad, 0x41, 0x5b, 0xaf, 0xb3, 0x81, 0x9d,
	0x81, 0x67, 0xda, 0x84, 0xa4, 0x12, 0x31, 0x53, 0x84, 0x7b, 0xb0, 0x39, 0xce, 0x56, 0x85, 0x55,
	0xb9, 0x60, 0x1c, 0x9c, 0xa1, 0xd4, 0x0e, 0x96, 0xf4, 0xb9, 0x22, 0x59, 0xa6, 0x67, 0x13, 0x3b,
	0x05, 0xd7, 0xf8, 0xff, 0x1f, 0x63, 0x4e, 0xc0, 0x19, 0xd1, 0x2b, 0xd5, 0x62, 0x7e, 0x57, 0x1d,
	0x82, 0x6b, 0xa8, 0x8a, 0x30, 0x1f, 0xd6, 0xd5, 0x3c, 0x8e, 0xb5, 0xc9, 0x42, 0xb4, 0x11, 0x7e,
	0x8f, 0xec, 0x00, 0xbc, 0x1b, 0x4a, 0x9f, 0xf4, 0xb1, 0xb9, 0x46, 0xad, 0x7a, 0xd1, 0x3d, 0xf4,
	0x2b, 0x8a, 0x22, 0x66, 0x89, 0xc4, 0xbc, 0x3a, 0xab, 0xc1, 0xb8, 0x7a, 0x47, 0x1b, 0xfe, 0xeb,
	0xa1, 0x1f, 0x80, 0xa5, 0x64, 0x65, 0x7c, 0x49, 0x46, 0xcb, 0x4e, 0x46, 0xfb, 0x07, 0x19, 0x66,
	0xf2, 0x5a, 0xe5, 0xd8, 0xa3, 0xcf, 0x16, 0xf4, 0x4c, 0x2e, 0x71, 0x08, 0x3d, 0x13, 0x25, 0xf4,
	0xb8, 0x15, 0xd1, 0xa0, 0xcf, 0xed, 0xcc, 0xb1, 0x06, 0x5e, 0xc0, 0x96, 0xc1, 0x09, 0xba, 0xdc,
	0xc6, 0x59, 0xe0, 0x71, 0x2b, 0x4e, 0x99, 0x83, 0x51, 0xbe, 0x76, 0xb0, 0x21, 0xa4, 0x1d, 0xac,
	0x8c, 0x68, 0x87, 0x6b, 0xd8, 0xae, 0x34, 0x8b, 0x7d, 0x6e, 0xa7, 0x23, 0xf0, 0xf9, 0x12, 0x08,
	0xb4, 0xcf, 0x39, 0x40, 0xd9, 0x0e, 0x22, 0xaf, 0xb5, 0x1b, 0xec, 0xf2, 0x7a, 0x7d, 0xac, 0x31,
	0xee, 0x2e, 0x3e, 0xf1, 0xe3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x52, 0xde, 0x0b, 0x68, 0xfa,
	0x03, 0x00, 0x00,
}
