// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BookingService.proto

package BookingService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KillBookingsShowMessage struct {
	ShowID               int32    `protobuf:"varint,1,opt,name=showID,proto3" json:"showID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillBookingsShowMessage) Reset()         { *m = KillBookingsShowMessage{} }
func (m *KillBookingsShowMessage) String() string { return proto.CompactTextString(m) }
func (*KillBookingsShowMessage) ProtoMessage()    {}
func (*KillBookingsShowMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{0}
}

func (m *KillBookingsShowMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillBookingsShowMessage.Unmarshal(m, b)
}
func (m *KillBookingsShowMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillBookingsShowMessage.Marshal(b, m, deterministic)
}
func (m *KillBookingsShowMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillBookingsShowMessage.Merge(m, src)
}
func (m *KillBookingsShowMessage) XXX_Size() int {
	return xxx_messageInfo_KillBookingsShowMessage.Size(m)
}
func (m *KillBookingsShowMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KillBookingsShowMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KillBookingsShowMessage proto.InternalMessageInfo

func (m *KillBookingsShowMessage) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

type KillBookingsShowResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillBookingsShowResponse) Reset()         { *m = KillBookingsShowResponse{} }
func (m *KillBookingsShowResponse) String() string { return proto.CompactTextString(m) }
func (*KillBookingsShowResponse) ProtoMessage()    {}
func (*KillBookingsShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{1}
}

func (m *KillBookingsShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillBookingsShowResponse.Unmarshal(m, b)
}
func (m *KillBookingsShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillBookingsShowResponse.Marshal(b, m, deterministic)
}
func (m *KillBookingsShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillBookingsShowResponse.Merge(m, src)
}
func (m *KillBookingsShowResponse) XXX_Size() int {
	return xxx_messageInfo_KillBookingsShowResponse.Size(m)
}
func (m *KillBookingsShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillBookingsShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillBookingsShowResponse proto.InternalMessageInfo

func (m *KillBookingsShowResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type KillBookingsUserMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillBookingsUserMessage) Reset()         { *m = KillBookingsUserMessage{} }
func (m *KillBookingsUserMessage) String() string { return proto.CompactTextString(m) }
func (*KillBookingsUserMessage) ProtoMessage()    {}
func (*KillBookingsUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{2}
}

func (m *KillBookingsUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillBookingsUserMessage.Unmarshal(m, b)
}
func (m *KillBookingsUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillBookingsUserMessage.Marshal(b, m, deterministic)
}
func (m *KillBookingsUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillBookingsUserMessage.Merge(m, src)
}
func (m *KillBookingsUserMessage) XXX_Size() int {
	return xxx_messageInfo_KillBookingsUserMessage.Size(m)
}
func (m *KillBookingsUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KillBookingsUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KillBookingsUserMessage proto.InternalMessageInfo

func (m *KillBookingsUserMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type KillBookingsUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillBookingsUserResponse) Reset()         { *m = KillBookingsUserResponse{} }
func (m *KillBookingsUserResponse) String() string { return proto.CompactTextString(m) }
func (*KillBookingsUserResponse) ProtoMessage()    {}
func (*KillBookingsUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{3}
}

func (m *KillBookingsUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillBookingsUserResponse.Unmarshal(m, b)
}
func (m *KillBookingsUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillBookingsUserResponse.Marshal(b, m, deterministic)
}
func (m *KillBookingsUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillBookingsUserResponse.Merge(m, src)
}
func (m *KillBookingsUserResponse) XXX_Size() int {
	return xxx_messageInfo_KillBookingsUserResponse.Size(m)
}
func (m *KillBookingsUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillBookingsUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillBookingsUserResponse proto.InternalMessageInfo

func (m *KillBookingsUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateBookingMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,2,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                []int32  `protobuf:"varint,3,rep,packed,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingMessage) Reset()         { *m = CreateBookingMessage{} }
func (m *CreateBookingMessage) String() string { return proto.CompactTextString(m) }
func (*CreateBookingMessage) ProtoMessage()    {}
func (*CreateBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{4}
}

func (m *CreateBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingMessage.Unmarshal(m, b)
}
func (m *CreateBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingMessage.Marshal(b, m, deterministic)
}
func (m *CreateBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingMessage.Merge(m, src)
}
func (m *CreateBookingMessage) XXX_Size() int {
	return xxx_messageInfo_CreateBookingMessage.Size(m)
}
func (m *CreateBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingMessage proto.InternalMessageInfo

func (m *CreateBookingMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateBookingMessage) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *CreateBookingMessage) GetSeats() []int32 {
	if m != nil {
		return m.Seats
	}
	return nil
}

type CreateBookingResponse struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingResponse) Reset()         { *m = CreateBookingResponse{} }
func (m *CreateBookingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookingResponse) ProtoMessage()    {}
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{5}
}

func (m *CreateBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingResponse.Unmarshal(m, b)
}
func (m *CreateBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingResponse.Merge(m, src)
}
func (m *CreateBookingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookingResponse.Size(m)
}
func (m *CreateBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingResponse proto.InternalMessageInfo

func (m *CreateBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type ConfirmBookingMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            int32    `protobuf:"varint,2,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmBookingMessage) Reset()         { *m = ConfirmBookingMessage{} }
func (m *ConfirmBookingMessage) String() string { return proto.CompactTextString(m) }
func (*ConfirmBookingMessage) ProtoMessage()    {}
func (*ConfirmBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{6}
}

func (m *ConfirmBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmBookingMessage.Unmarshal(m, b)
}
func (m *ConfirmBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmBookingMessage.Marshal(b, m, deterministic)
}
func (m *ConfirmBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmBookingMessage.Merge(m, src)
}
func (m *ConfirmBookingMessage) XXX_Size() int {
	return xxx_messageInfo_ConfirmBookingMessage.Size(m)
}
func (m *ConfirmBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmBookingMessage proto.InternalMessageInfo

func (m *ConfirmBookingMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ConfirmBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type ConfirmBookingResponse struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmBookingResponse) Reset()         { *m = ConfirmBookingResponse{} }
func (m *ConfirmBookingResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmBookingResponse) ProtoMessage()    {}
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{7}
}

func (m *ConfirmBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmBookingResponse.Unmarshal(m, b)
}
func (m *ConfirmBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmBookingResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmBookingResponse.Merge(m, src)
}
func (m *ConfirmBookingResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmBookingResponse.Size(m)
}
func (m *ConfirmBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmBookingResponse proto.InternalMessageInfo

func (m *ConfirmBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type DeleteBookingMessage struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingMessage) Reset()         { *m = DeleteBookingMessage{} }
func (m *DeleteBookingMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingMessage) ProtoMessage()    {}
func (*DeleteBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{8}
}

func (m *DeleteBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingMessage.Unmarshal(m, b)
}
func (m *DeleteBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingMessage.Marshal(b, m, deterministic)
}
func (m *DeleteBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingMessage.Merge(m, src)
}
func (m *DeleteBookingMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingMessage.Size(m)
}
func (m *DeleteBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingMessage proto.InternalMessageInfo

func (m *DeleteBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type DeleteBookingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingResponse) Reset()         { *m = DeleteBookingResponse{} }
func (m *DeleteBookingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingResponse) ProtoMessage()    {}
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{9}
}

func (m *DeleteBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingResponse.Unmarshal(m, b)
}
func (m *DeleteBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingResponse.Merge(m, src)
}
func (m *DeleteBookingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingResponse.Size(m)
}
func (m *DeleteBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingResponse proto.InternalMessageInfo

func (m *DeleteBookingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserBookingsMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBookingsMessage) Reset()         { *m = GetUserBookingsMessage{} }
func (m *GetUserBookingsMessage) String() string { return proto.CompactTextString(m) }
func (*GetUserBookingsMessage) ProtoMessage()    {}
func (*GetUserBookingsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{10}
}

func (m *GetUserBookingsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBookingsMessage.Unmarshal(m, b)
}
func (m *GetUserBookingsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBookingsMessage.Marshal(b, m, deterministic)
}
func (m *GetUserBookingsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBookingsMessage.Merge(m, src)
}
func (m *GetUserBookingsMessage) XXX_Size() int {
	return xxx_messageInfo_GetUserBookingsMessage.Size(m)
}
func (m *GetUserBookingsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBookingsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBookingsMessage proto.InternalMessageInfo

func (m *GetUserBookingsMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserBookingsResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            []int32  `protobuf:"varint,2,rep,packed,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBookingsResponse) Reset()         { *m = GetUserBookingsResponse{} }
func (m *GetUserBookingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserBookingsResponse) ProtoMessage()    {}
func (*GetUserBookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{11}
}

func (m *GetUserBookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBookingsResponse.Unmarshal(m, b)
}
func (m *GetUserBookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBookingsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserBookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBookingsResponse.Merge(m, src)
}
func (m *GetUserBookingsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserBookingsResponse.Size(m)
}
func (m *GetUserBookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBookingsResponse proto.InternalMessageInfo

func (m *GetUserBookingsResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetUserBookingsResponse) GetBookingID() []int32 {
	if m != nil {
		return m.BookingID
	}
	return nil
}

type GetBookingMessage struct {
	BookingID            int32    `protobuf:"varint,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingMessage) Reset()         { *m = GetBookingMessage{} }
func (m *GetBookingMessage) String() string { return proto.CompactTextString(m) }
func (*GetBookingMessage) ProtoMessage()    {}
func (*GetBookingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{12}
}

func (m *GetBookingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingMessage.Unmarshal(m, b)
}
func (m *GetBookingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingMessage.Marshal(b, m, deterministic)
}
func (m *GetBookingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingMessage.Merge(m, src)
}
func (m *GetBookingMessage) XXX_Size() int {
	return xxx_messageInfo_GetBookingMessage.Size(m)
}
func (m *GetBookingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingMessage proto.InternalMessageInfo

func (m *GetBookingMessage) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type GetBookingResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,2,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                []int32  `protobuf:"varint,3,rep,packed,name=seats,proto3" json:"seats,omitempty"`
	BookingID            int32    `protobuf:"varint,4,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookingResponse) Reset()         { *m = GetBookingResponse{} }
func (m *GetBookingResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookingResponse) ProtoMessage()    {}
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbbe29f60712d30, []int{13}
}

func (m *GetBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookingResponse.Unmarshal(m, b)
}
func (m *GetBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookingResponse.Marshal(b, m, deterministic)
}
func (m *GetBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookingResponse.Merge(m, src)
}
func (m *GetBookingResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookingResponse.Size(m)
}
func (m *GetBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookingResponse proto.InternalMessageInfo

func (m *GetBookingResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetBookingResponse) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *GetBookingResponse) GetSeats() []int32 {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *GetBookingResponse) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

func init() {
	proto.RegisterType((*KillBookingsShowMessage)(nil), "KillBookingsShowMessage")
	proto.RegisterType((*KillBookingsShowResponse)(nil), "KillBookingsShowResponse")
	proto.RegisterType((*KillBookingsUserMessage)(nil), "KillBookingsUserMessage")
	proto.RegisterType((*KillBookingsUserResponse)(nil), "KillBookingsUserResponse")
	proto.RegisterType((*CreateBookingMessage)(nil), "CreateBookingMessage")
	proto.RegisterType((*CreateBookingResponse)(nil), "CreateBookingResponse")
	proto.RegisterType((*ConfirmBookingMessage)(nil), "ConfirmBookingMessage")
	proto.RegisterType((*ConfirmBookingResponse)(nil), "ConfirmBookingResponse")
	proto.RegisterType((*DeleteBookingMessage)(nil), "DeleteBookingMessage")
	proto.RegisterType((*DeleteBookingResponse)(nil), "DeleteBookingResponse")
	proto.RegisterType((*GetUserBookingsMessage)(nil), "GetUserBookingsMessage")
	proto.RegisterType((*GetUserBookingsResponse)(nil), "GetUserBookingsResponse")
	proto.RegisterType((*GetBookingMessage)(nil), "GetBookingMessage")
	proto.RegisterType((*GetBookingResponse)(nil), "GetBookingResponse")
}

func init() { proto.RegisterFile("BookingService.proto", fileDescriptor_5dbbe29f60712d30) }

var fileDescriptor_5dbbe29f60712d30 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x4f, 0xc2, 0x40,
	0x14, 0x04, 0x2a, 0xa8, 0x2f, 0x11, 0x75, 0x2d, 0x6d, 0x6d, 0x3c, 0x90, 0x3d, 0x79, 0xda, 0x88,
	0xa2, 0x5e, 0x8d, 0x10, 0x0d, 0x31, 0xc4, 0x04, 0xe2, 0xcd, 0x0b, 0x90, 0x15, 0x1b, 0x91, 0x25,
	0x5d, 0x50, 0x7f, 0xb6, 0x3f, 0xc1, 0xc7, 0x67, 0xbb, 0xdb, 0x45, 0xca, 0xf1, 0x2d, 0xcc, 0xcc,
	0xdb, 0x9d, 0xe9, 0x80, 0x7d, 0x2f, 0xc4, 0x47, 0x30, 0xec, 0xb7, 0x79, 0xf8, 0x15, 0xf4, 0x38,
	0x1b, 0x85, 0x62, 0x2c, 0x68, 0x05, 0xdc, 0xa7, 0x60, 0x30, 0x58, 0xfc, 0x26, 0xdb, 0xef, 0xe2,
	0xbb, 0xc9, 0xa5, 0xec, 0xf4, 0x39, 0x71, 0xa0, 0x20, 0x71, 0x6c, 0xd4, 0xbd, 0x6c, 0x39, 0x7b,
	0x9e, 0x6f, 0x2d, 0x26, 0x5a, 0x05, 0x4f, 0x87, 0xb4, 0xb8, 0x1c, 0x89, 0xa1, 0xe4, 0xc4, 0x83,
	0x5d, 0x39, 0xe9, 0xf5, 0x90, 0x61, 0x06, 0xda, 0x6b, 0x2d, 0x47, 0x5d, 0xe8, 0x45, 0xf2, 0x30,
	0x26, 0x34, 0xc1, 0x31, 0x12, 0x9a, 0x4f, 0xba, 0xd0, 0x14, 0x92, 0x42, 0xe8, 0x15, 0xec, 0x5a,
	0xc8, 0x3b, 0x63, 0xbe, 0xc0, 0x6d, 0x50, 0x89, 0x5d, 0x33, 0x17, 0xbf, 0x26, 0xb1, 0x21, 0x2f,
	0x91, 0x46, 0x7a, 0x56, 0xd9, 0xc2, 0xe3, 0xf9, 0x40, 0xaf, 0xa1, 0xa4, 0xb0, 0xaf, 0x16, 0x3a,
	0x83, 0xfd, 0xee, 0xfc, 0x68, 0xa5, 0x10, 0x1d, 0xd0, 0x26, 0xc2, 0xc4, 0xf0, 0x2d, 0x08, 0x3f,
	0x53, 0x6e, 0xa5, 0xd0, 0xe5, 0x74, 0xba, 0x1b, 0x70, 0x54, 0xba, 0x94, 0x6b, 0x54, 0xc1, 0xae,
	0xf3, 0x01, 0x4f, 0xbc, 0xcd, 0xff, 0xa8, 0x0a, 0x94, 0x14, 0x54, 0x0a, 0x13, 0x2e, 0xc0, 0x79,
	0xe4, 0xe3, 0xa9, 0x63, 0x4b, 0xf7, 0x36, 0x99, 0xfd, 0x0c, 0xae, 0x86, 0x58, 0xc9, 0xa4, 0x7c,
	0x23, 0x4b, 0xdf, 0xfa, 0x18, 0x09, 0xb7, 0xba, 0xe8, 0x0f, 0x90, 0x08, 0xb2, 0x51, 0x7e, 0xab,
	0xe0, 0xa8, 0xca, 0x3b, 0x9a, 0xf2, 0xe5, 0xaf, 0x05, 0x45, 0xf5, 0xfb, 0x24, 0x77, 0x70, 0xa0,
	0x24, 0x8d, 0x94, 0x98, 0x29, 0xd7, 0xbe, 0xc3, 0x8c, 0x81, 0xa4, 0x19, 0x52, 0x83, 0xa2, 0x9a,
	0x12, 0x82, 0xff, 0x35, 0xa5, 0xd0, 0x77, 0x99, 0x39, 0x4e, 0x48, 0x82, 0x6b, 0x28, 0xe6, 0xe3,
	0x1a, 0xa6, 0x08, 0xe1, 0x1a, 0xc6, 0x8c, 0x20, 0xc3, 0x03, 0x1c, 0x6a, 0xce, 0x12, 0x97, 0x99,
	0xd3, 0xe1, 0x7b, 0x6c, 0x4d, 0x08, 0x90, 0xe7, 0x16, 0x20, 0x72, 0x87, 0x10, 0x96, 0x70, 0xd7,
	0x3f, 0x61, 0x49, 0xfb, 0x10, 0xd8, 0x80, 0x23, 0xbd, 0x47, 0x88, 0xc7, 0xd6, 0xb4, 0x91, 0x7f,
	0xca, 0xd6, 0x95, 0x4e, 0x92, 0x6a, 0xda, 0x7d, 0x1a, 0x55, 0xac, 0x41, 0x35, 0xaa, 0x78, 0x51,
	0xd2, 0x4c, 0xb7, 0x30, 0x2b, 0xe0, 0xab, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x51, 0x7a,
	0xe1, 0x98, 0x05, 0x00, 0x00,
}
