// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserService.proto

package UserService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserMessage) Reset()         { *m = CreateUserMessage{} }
func (m *CreateUserMessage) String() string { return proto.CompactTextString(m) }
func (*CreateUserMessage) ProtoMessage()    {}
func (*CreateUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{0}
}

func (m *CreateUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserMessage.Unmarshal(m, b)
}
func (m *CreateUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserMessage.Marshal(b, m, deterministic)
}
func (m *CreateUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserMessage.Merge(m, src)
}
func (m *CreateUserMessage) XXX_Size() int {
	return xxx_messageInfo_CreateUserMessage.Size(m)
}
func (m *CreateUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserMessage proto.InternalMessageInfo

func (m *CreateUserMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateUserMessage) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type CreateUserResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type DeleteUserMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserMessage) Reset()         { *m = DeleteUserMessage{} }
func (m *DeleteUserMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteUserMessage) ProtoMessage()    {}
func (*DeleteUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{2}
}

func (m *DeleteUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserMessage.Unmarshal(m, b)
}
func (m *DeleteUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserMessage.Marshal(b, m, deterministic)
}
func (m *DeleteUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserMessage.Merge(m, src)
}
func (m *DeleteUserMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteUserMessage.Size(m)
}
func (m *DeleteUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserMessage proto.InternalMessageInfo

func (m *DeleteUserMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type DeleteUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{3}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserMessage struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserMessage) Reset()         { *m = GetUserMessage{} }
func (m *GetUserMessage) String() string { return proto.CompactTextString(m) }
func (*GetUserMessage) ProtoMessage()    {}
func (*GetUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{4}
}

func (m *GetUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserMessage.Unmarshal(m, b)
}
func (m *GetUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserMessage.Marshal(b, m, deterministic)
}
func (m *GetUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserMessage.Merge(m, src)
}
func (m *GetUserMessage) XXX_Size() int {
	return xxx_messageInfo_GetUserMessage.Size(m)
}
func (m *GetUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserMessage proto.InternalMessageInfo

func (m *GetUserMessage) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{5}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetUserResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserMessage)(nil), "CreateUserMessage")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
	proto.RegisterType((*DeleteUserMessage)(nil), "DeleteUserMessage")
	proto.RegisterType((*DeleteUserResponse)(nil), "DeleteUserResponse")
	proto.RegisterType((*GetUserMessage)(nil), "GetUserMessage")
	proto.RegisterType((*GetUserResponse)(nil), "GetUserResponse")
}

func init() { proto.RegisterFile("UserService.proto", fileDescriptor_e7864342a5dd7108) }

var fileDescriptor_e7864342a5dd7108 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0x2d, 0x4e, 0x2d,
	0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe7,
	0x12, 0x74, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x05, 0x49, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x0a, 0x89, 0x71, 0xb1, 0x95, 0x02, 0xb9, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x50, 0x9e, 0x90, 0x14, 0x17, 0x07, 0x88, 0xe5, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x94, 0xe1,
	0x0c, 0x82, 0xf3, 0x95, 0x74, 0xb8, 0x84, 0x10, 0x06, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15,
	0xe3, 0x34, 0x49, 0x49, 0x9b, 0x4b, 0xd0, 0x25, 0x35, 0x27, 0x95, 0x28, 0x6b, 0x95, 0xf4, 0xb8,
	0x84, 0x10, 0x8a, 0xe1, 0x46, 0x4b, 0x70, 0xb1, 0x17, 0x97, 0x26, 0x27, 0x03, 0xf5, 0x82, 0x95,
	0x73, 0x04, 0xc1, 0xb8, 0x4a, 0x1a, 0x5c, 0x7c, 0xee, 0xa9, 0x25, 0xc4, 0x98, 0xec, 0xca, 0xc5,
	0x0f, 0x55, 0x49, 0xc8, 0xc5, 0xf8, 0xfc, 0x6e, 0xb4, 0x9e, 0x91, 0x8b, 0x1b, 0x29, 0x68, 0x85,
	0xcc, 0xb9, 0xb8, 0x10, 0x61, 0x21, 0x24, 0xa4, 0x87, 0x11, 0xc2, 0x52, 0xc2, 0x7a, 0x98, 0x81,
	0xa5, 0xc4, 0x00, 0xd2, 0x88, 0xf0, 0x29, 0x50, 0x23, 0x46, 0x18, 0x01, 0x35, 0x62, 0x06, 0x05,
	0x50, 0xa3, 0x1e, 0x17, 0x3b, 0xd4, 0x23, 0x42, 0xfc, 0x7a, 0xa8, 0x9e, 0x97, 0x12, 0xd0, 0x43,
	0xf3, 0xa3, 0x12, 0x43, 0x12, 0x1b, 0x38, 0xf6, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3c,
	0x8f, 0xb0, 0xf4, 0x12, 0x02, 0x00, 0x00,
}
