// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MovieService.proto

package MovieService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMovieMessage struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieMessage) Reset()         { *m = CreateMovieMessage{} }
func (m *CreateMovieMessage) String() string { return proto.CompactTextString(m) }
func (*CreateMovieMessage) ProtoMessage()    {}
func (*CreateMovieMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_234797cf09162827, []int{0}
}

func (m *CreateMovieMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieMessage.Unmarshal(m, b)
}
func (m *CreateMovieMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieMessage.Marshal(b, m, deterministic)
}
func (m *CreateMovieMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieMessage.Merge(m, src)
}
func (m *CreateMovieMessage) XXX_Size() int {
	return xxx_messageInfo_CreateMovieMessage.Size(m)
}
func (m *CreateMovieMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieMessage proto.InternalMessageInfo

func (m *CreateMovieMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateMovieResponse struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=MovieID,proto3" json:"MovieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieResponse) Reset()         { *m = CreateMovieResponse{} }
func (m *CreateMovieResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResponse) ProtoMessage()    {}
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234797cf09162827, []int{1}
}

func (m *CreateMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResponse.Unmarshal(m, b)
}
func (m *CreateMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResponse.Marshal(b, m, deterministic)
}
func (m *CreateMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResponse.Merge(m, src)
}
func (m *CreateMovieResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResponse.Size(m)
}
func (m *CreateMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResponse proto.InternalMessageInfo

func (m *CreateMovieResponse) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

type DeleteMovieMessage struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=MovieID,proto3" json:"MovieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieMessage) Reset()         { *m = DeleteMovieMessage{} }
func (m *DeleteMovieMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieMessage) ProtoMessage()    {}
func (*DeleteMovieMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_234797cf09162827, []int{2}
}

func (m *DeleteMovieMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieMessage.Unmarshal(m, b)
}
func (m *DeleteMovieMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieMessage.Marshal(b, m, deterministic)
}
func (m *DeleteMovieMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieMessage.Merge(m, src)
}
func (m *DeleteMovieMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieMessage.Size(m)
}
func (m *DeleteMovieMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieMessage proto.InternalMessageInfo

func (m *DeleteMovieMessage) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

type DeleteMovieResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResponse) Reset()         { *m = DeleteMovieResponse{} }
func (m *DeleteMovieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResponse) ProtoMessage()    {}
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234797cf09162827, []int{3}
}

func (m *DeleteMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResponse.Unmarshal(m, b)
}
func (m *DeleteMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResponse.Merge(m, src)
}
func (m *DeleteMovieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResponse.Size(m)
}
func (m *DeleteMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResponse proto.InternalMessageInfo

func (m *DeleteMovieResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetMovieMessage struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=MovieID,proto3" json:"MovieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieMessage) Reset()         { *m = GetMovieMessage{} }
func (m *GetMovieMessage) String() string { return proto.CompactTextString(m) }
func (*GetMovieMessage) ProtoMessage()    {}
func (*GetMovieMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_234797cf09162827, []int{4}
}

func (m *GetMovieMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieMessage.Unmarshal(m, b)
}
func (m *GetMovieMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieMessage.Marshal(b, m, deterministic)
}
func (m *GetMovieMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieMessage.Merge(m, src)
}
func (m *GetMovieMessage) XXX_Size() int {
	return xxx_messageInfo_GetMovieMessage.Size(m)
}
func (m *GetMovieMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieMessage proto.InternalMessageInfo

func (m *GetMovieMessage) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

type GetMovieResponse struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=MovieID,proto3" json:"MovieID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieResponse) Reset()         { *m = GetMovieResponse{} }
func (m *GetMovieResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieResponse) ProtoMessage()    {}
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234797cf09162827, []int{5}
}

func (m *GetMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieResponse.Unmarshal(m, b)
}
func (m *GetMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieResponse.Marshal(b, m, deterministic)
}
func (m *GetMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieResponse.Merge(m, src)
}
func (m *GetMovieResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieResponse.Size(m)
}
func (m *GetMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieResponse proto.InternalMessageInfo

func (m *GetMovieResponse) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *GetMovieResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMovieMessage)(nil), "CreateMovieMessage")
	proto.RegisterType((*CreateMovieResponse)(nil), "CreateMovieResponse")
	proto.RegisterType((*DeleteMovieMessage)(nil), "DeleteMovieMessage")
	proto.RegisterType((*DeleteMovieResponse)(nil), "DeleteMovieResponse")
	proto.RegisterType((*GetMovieMessage)(nil), "GetMovieMessage")
	proto.RegisterType((*GetMovieResponse)(nil), "GetMovieResponse")
}

func init() { proto.RegisterFile("MovieService.proto", fileDescriptor_234797cf09162827) }

var fileDescriptor_234797cf09162827 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xf2, 0xcd, 0x2f, 0xcb,
	0x4c, 0x0d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2,
	0xe2, 0x12, 0x72, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x05, 0xcb, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6,
	0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xe4, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x41, 0x38, 0x4a, 0xfa, 0x5c, 0xc2, 0x48, 0x6a, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x24, 0xb8, 0xd8, 0xc1, 0x02, 0x9e, 0x2e, 0x60, 0xe5, 0xac, 0x41, 0x30, 0xae, 0x92,
	0x1e, 0x97, 0x90, 0x4b, 0x6a, 0x4e, 0x2a, 0x9a, 0xe1, 0xb8, 0xd5, 0x03, 0x2d, 0x40, 0x52, 0x8f,
	0x6c, 0x41, 0x71, 0x69, 0x72, 0x32, 0x50, 0x3b, 0x58, 0x03, 0x47, 0x10, 0x8c, 0xab, 0xa4, 0xcd,
	0xc5, 0xef, 0x9e, 0x5a, 0x42, 0xa4, 0xe9, 0x4e, 0x5c, 0x02, 0x30, 0xc5, 0x84, 0xdd, 0x8e, 0x08,
	0x02, 0x26, 0xa4, 0x20, 0x30, 0xda, 0xc9, 0xc8, 0xc5, 0x83, 0x1c, 0x8a, 0x42, 0x56, 0x5c, 0xdc,
	0x48, 0x61, 0x22, 0x24, 0xac, 0x87, 0x19, 0x9a, 0x52, 0x22, 0x7a, 0x58, 0x82, 0x4d, 0x89, 0x01,
	0xa4, 0x17, 0xc9, 0xbb, 0x40, 0xbd, 0x98, 0x81, 0x05, 0xd4, 0x8b, 0x25, 0x44, 0x80, 0x7a, 0x0d,
	0xb9, 0x38, 0x60, 0x9e, 0x11, 0x12, 0xd0, 0x43, 0x0b, 0x04, 0x29, 0x41, 0x3d, 0x74, 0x9f, 0x2a,
	0x31, 0x24, 0xb1, 0x81, 0x63, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xff, 0xca, 0xd8, 0xf2,
	0x07, 0x02, 0x00, 0x00,
}
